# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-19 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpapp', '0003_auto_20200119_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdata',
            name='precipitaton',
            field=models.FloatField(null=True, verbose_name=b'precipitation'),
        ),
    ]
