# Generated by Django 2.2.2 on 2020-01-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpapp', '0007_auto_20200119_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdata',
            name='month',
            field=models.IntegerField(verbose_name='month'),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='precipitation',
            field=models.FloatField(null=True, verbose_name='precipitation'),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='temperature',
            field=models.FloatField(verbose_name='temperature'),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='year',
            field=models.IntegerField(verbose_name='year'),
        ),
    ]
